name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "*.md"
  push:
    branches:
      - feats/workflows/pull

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install Bun
        run: npm i bun -g

      - name: Install dependencies
        run: bun install

      - name: Build typescript files
        run: npm run build
        
